[project]
name = "openai-agents-events"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "logfire>=3.12.0",
    "openai-agents>=0.0.7",
]
